spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  application:
    name: Ases Backend
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator

jwt:
  secret: ${JWT_SECRET}
